#!/bin/sh

# 1. Monta os sistemas de arquivos essenciais do Kernel
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# 2. Configura a rede local (Loopback)
ifconfig lo 127.0.0.1 up

# 3. Inicia o barramento do sistema (D-Bus), necessário para a rede e áudio
mkdir -p /run/dbus
dbus-daemon --system --fork

# 4. Inicia o gerenciador de rede para pegar IP automático via DHCP
NetworkManager &

# 5. Inicia o áudio
pipewire &
wireplumber &

# 6. Inicia a interface gráfica e o gerenciador de usuários
exec lightdm
